appName = "go-blog"

[mysql]
host = "127.0.0.1"
port = 3306
name = "blog"
user = "root"
password = "bunch1234"
timeout = "10s"

[log]
level = "debug"
path = "logs/blog.log"

[staticPath]
filePath = "web/static/file/"

[msgChannelType]
channelType = "gochannel"