const tailFormItemLayout = {
    wrapperCol: {
    xs: {
        span: 10,
        offset: 0,
    },
    sm: {
        span: 10,
        offset: 8,
    },
    },
}

const tailFormButtonLayout = {
    wrapperCol: {
    xs: {
        span: 8,
        offset: 0,
    },
    sm: {
        span: 7,
        offset: 8,
    },
    },
}

const residences = [
    {
        name: '安徽',
        items: [
            {name: '安庆'},
            {name: '蚌埠'},
            {name: '豪州'},
            {name: '池州'},
            {name: '滁州'},
            {name: '阜阳'},
            {name: '合肥'},
            {name: '淮北'},
            {name: '淮南'},
            {name: '黄山'},
            {name: '六安'},
            {name: '马鞍山'},
            {name: '宿州'},
            {name: '铜陵'},
            {name: '芜湖'},
            {name: '宣城'},
        ],
    },
    {
        name: '北京',
        items: [
            {name: '昌平'},
            {name: '朝阳'},
            {name: '大兴'},
            {name: '东城'},
            {name: '房山'},
            {name: '丰台'},
            {name: '海淀'},
            {name: '怀柔'},
            {name: '门头沟'},
            {name: '密云'},
            {name: '平谷'},
            {name: '石景山'},
            {name: '顺义'},
            {name: '通州'},
            {name: '西城'},
            {name: '延庆'},
        ],
    },
    {
        name: '重庆',
        items: [
            {name: '巴南'},
            {name: '北碚'},
            {name: '璧山'},
            {name: '长寿'},
            {name: '城口'},
            {name: '大渡口'},
            {name: '大足区'},
            {name: '垫江'},
            {name: '丰都'},
            {name: '奉节'},
            {name: '涪陵'},
            {name: '合川'},
            {name: '江北'},
            {name: '江津'},
            {name: '九龙坡'},
            {name: '开州区'},
            {name: '两江新区'},
            {name: '梁平'},
            {name: '南岸'},
            {name: '南川'},
            {name: '彭水'},
            {name: '綦江区'},
            {name: '黔江'},
            {name: '荣昌'},
            {name: '沙坪坝'},
            {name: '石柱'},
            {name: '铜梁'},
            {name: '潼南'},
            {name: '万州'},
            {name: '武隆'},
            {name: '巫山'},
            {name: '巫溪'},
            {name: '秀山'},
            {name: '永川'},
            {name: '酉阳'},
            {name: '渝北'},
            {name: '渝中'},
            {name: '云阳'},
            {name: '忠县'},
        ],
    },
    {
        name: '福建',
        items: [
            {name: '福州'},
            {name: '龙岩'},
            {name: '南平'},
            {name: '宁德'},
            {name: '莆田'},
            {name: '泉州'},
            {name: '三明'},
            {name: '厦门'},
            {name: '漳州'},
        ],
    },
    {
        name: '甘肃',
        items: [
            {name: '白银'},
            {name: '定西'},
            {name: '甘南'},
            {name: '嘉峪关'},
            {name: '金昌'},
            {name: '酒泉'},
            {name: '兰州'},
            {name: '临夏'},
            {name: '陇南'},
            {name: '平凉'},
            {name: '庆阳'},
            {name: '天水'},
            {name: '武威'},
            {name: '张掖'},
        ],
    },
    {
        name: '广东',
        items: [
            {name: '潮州'},
            {name: '东莞'},
            {name: '佛山'},
            {name: '广州'},
            {name: '河源'},
            {name: '惠州'},
            {name: '江门'},
            {name: '揭阳'},
            {name: '茂名'},
            {name: '梅州'},
            {name: '清远'},
            {name: '汕头'},
            {name: '汕尾'},
            {name: '韶关'},
            {name: '深圳'},
            {name: '阳江'},
            {name: '云浮'},
            {name: '湛江'},
            {name: '肇庆'},
            {name: '中山'},
            {name: '珠海'},
        ],
    },
    {
        name: '广西',
        items: [
            {name: '百色'},
            {name: '北海'},
            {name: '崇左'},
            {name: '防城港'},
            {name: '贵港'},
            {name: '桂林'},
            {name: '河池'},
            {name: '贺州'},
            {name: '来宾'},
            {name: '柳州'},
            {name: '南宁'},
            {name: '钦州'},
            {name: '梧州'},
            {name: '玉林'},
        ],
    },
    {
        name: '贵州',
        items: [
            {name: '安顺'},
            {name: '毕节'},
            {name: '贵阳'},
            {name: '六盘水'},
            {name: '黔东南'},
            {name: '黔南'},
            {name: '黔西南'},
            {name: '铜仁'},
            {name: '遵义'},
        ],
    },
    {
        name: '海南',
        items: [
            {name: '白沙'},
            {name: '保亭'},
            {name: '昌江'},
            {name: '澄迈'},
            {name: '儋州'},
            {name: '定安'},
            {name: '东方'},
            {name: '海口'},
            {name: '乐东'},
            {name: '临高'},
            {name: '陵水'},
            {name: '琼海'},
            {name: '琼中'},
            {name: '三沙'},
            {name: '三亚'},
            {name: '屯昌'},
            {name: '万宁'},
            {name: '文昌'},
            {name: '五指山'},
        ],
    },
    {
        name: '河北',
        items: [
            {name: '保定'},
            {name: '沧州'},
            {name: '承德'},
            {name: '邯郸'},
            {name: '衡水'},
            {name: '廊坊'},
            {name: '秦皇岛'},
            {name: '石家庄'},
            {name: '唐山'},
            {name: '邢台'},
            {name: '张家口'},
        ],
    },
    {
        name: '河南',
        items: [
            {name: '安阳'},
            {name: '鹤壁'},
            {name: '济源'},
            {name: '焦作'},
            {name: '开封'},
            {name: '洛阳'},
            {name: '南阳'},
            {name: '平顶山'},
            {name: '濮阳'},
            {name: '三门峡'},
            {name: '商丘'},
            {name: '漯河'},
            {name: '新乡'},
            {name: '信阳'},
            {name: '许昌'},
            {name: '郑州'},
            {name: '周口'},
            {name: '驻马店'},
        ],
    },
    {
        name: '黑龙江',
        items: [
            {name: '大庆'},
            {name: '大兴安岭'},
            {name: '哈尔滨'},
            {name: '鹤岗'},
            {name: '黑河'},
            {name: '鸡西'},
            {name: '佳木斯'},
            {name: '牡丹江'},
            {name: '齐齐哈尔'},
            {name: '七台河'},
            {name: '双鸭山'},
            {name: '绥化'},
            {name: '伊春'},
        ],
    },
    {
        name: '湖北',
        items: [
            {name: '鄂州'},
            {name: '恩施'},
            {name: '黄冈'},
            {name: '黄石'},
            {name: '荆门'},
            {name: '潜江'},
            {name: '神农架'},
            {name: '十堰'},
            {name: '随州'},
            {name: '天门'},
            {name: '武汉'},
            {name: '咸宁'},
            {name: '仙桃'},
            {name: '襄阳'},
            {name: '孝感'},
            {name: '宜昌'},
        ],
    },
    {
        name: '湖南',
        items: [
            {name: '常德'},
            {name: '长沙'},
            {name: '郴州'},
            {name: '衡阳'},
            {name: '怀化'},
            {name: '娄底'},
            {name: '邵阳'},
            {name: '湘潭'},
            {name: '湘西'},
            {name: '益阳'},
            {name: '永州'},
            {name: '岳阳'},
            {name: '张家界'},
            {name: '株洲'},
        ],
    },
    {
        name: '吉林',
        items: [
            {name: '白城'},
            {name: '白山'},
            {name: '长春'},
            {name: '吉林'},
            {name: '辽源'},
            {name: '四平'},
            {name: '松原'},
            {name: '通化'},
            {name: '延边'},
        ],
    },
    {
        name: '江苏',
        items: [
            {name: '常州'},
            {name: '淮安'},
            {name: '连云港'},
            {name: '南京'},
            {name: '南通'},
            {name: '宿迁'},
            {name: '苏州'},
            {name: '泰州'},
            {name: '无锡'},
            {name: '徐州'},
            {name: '盐城'},
            {name: '扬州'},
            {name: '镇江'},
        ],
    },
    {
        name: '江西',
        items: [
            {name: '抚州'},
            {name: '赣州'},
            {name: '吉安'},
            {name: '景德镇'},
            {name: '九江'},
            {name: '南昌'},
            {name: '萍乡'},
            {name: '上饶'},
            {name: '新余'},
            {name: '宜春'},
            {name: '鹰潭'},
        ],
    },
    {
        name: '辽宁',
        items: [
            {name: '鞍山'},
            {name: '本溪'},
            {name: '朝阳'},
            {name: '大连'},
            {name: '丹东'},
            {name: '抚顺'},
            {name: '阜新'},
            {name: '葫芦岛'},
            {name: '锦州'},
            {name: '辽阳'},
            {name: '盘锦'},
            {name: '沈阳'},
            {name: '铁岭'},
            {name: '营口'},
        ],
    },
    {
        name: '内蒙古',
        items: [
            {name: '阿拉善'},
            {name: '巴彦淖尔'},
            {name: '包头'},
            {name: '赤峰'},
            {name: '鄂尔多斯'},
            {name: '呼和浩特'},
            {name: '呼伦贝尔'},
            {name: '通辽'},
            {name: '乌海'},
            {name: '乌兰察布'},
            {name: '锡林郭勒'},
            {name: '兴安'},
        ],
    },
    {
        name: '宁夏',
        items: [
            {name: '固原'},
            {name: '石嘴山'},
            {name: '吴忠'},
            {name: '银川'},
            {name: '中卫'},
        ],
    },
    {
        name: '青海',
        items: [
            {name: '果洛'},
            {name: '海北'},
            {name: '海东'},
            {name: '海南'},
            {name: '海西'},
            {name: '黄南'},
            {name: '西宁'},
            {name: '玉树'},
        ],
    },
    {
        name: '山东',
        items: [
            {name: '滨州'},
            {name: '德州'},
            {name: '东营'},
            {name: '菏泽'},
            {name: '济南'},
            {name: '济宁'},
            {name: '莱芜区'},
            {name: '聊城'},
            {name: '临沂'},
            {name: '青岛'},
            {name: '日照'},
            {name: '泰安'},
            {name: '潍坊'},
            {name: '威海'},
            {name: '烟台'},
            {name: '枣庄'},
            {name: '淄博'},
        ],
    },
    {
        name: '山西',
        items: [
            {name: '长治'},
            {name: '大同'},
            {name: '晋城'},
            {name: '晋中'},
            {name: '临汾'},
            {name: '吕梁'},
            {name: '朔州'},
            {name: '太原'},
            {name: '忻州'},
            {name: '阳泉'},
            {name: '运城'},
        ],
    },
    {
        name: '陕西',
        items: [
            {name: '安康'},
            {name: '宝鸡'},
            {name: '汉中'},
            {name: '商洛'},
            {name: '铜川'},
            {name: '渭南'},
            {name: '西安'},
            {name: '咸阳'},
            {name: '延安'},
            {name: '榆林'},
        ],
    },
    {
        name: '上海',
        items: [
            {name: '宝山'},
            {name: '长宁'},
            {name: '崇明'},
            {name: '奉贤'},
            {name: '虹口'},
            {name: '黄埔'},
            {name: '嘉定'},
            {name: '金山'},
            {name: '静安'},
            {name: '闵行'},
            {name: '浦东新区'},
            {name: '普陀'},
            {name: '青浦'},
            {name: '松江'},
            {name: '徐汇'},
            {name: '杨浦'},
        ],
    },
    {
        name: '四川',
        items: [
            {name: '阿坝'},
            {name: '巴中'},
            {name: '成都'},
            {name: '达州'},
            {name: '德阳'},
            {name: '甘孜'},
            {name: '广安'},
            {name: '广元'},
            {name: '乐山'},
            {name: '凉山'},
            {name: '泸州'},
            {name: '眉山'},
            {name: '绵阳'},
            {name: '南充'},
            {name: '内江'},
            {name: '攀枝花'},
            {name: '遂宁'},
            {name: '雅安'},
            {name: '宜宾'},
            {name: '自贡'},
            {name: '资阳'},
        ],
    },
    {
        name: '天津',
        items: [
            {name: '宝坻'},
            {name: '北辰'},
            {name: '滨海新区'},
            {name: '东丽'},
            {name: '河北'},
            {name: '河东'},
            {name: '和平'},
            {name: '河西'},
            {name: '红桥'},
            {name: '蓟州'},
            {name: '津南'},
            {name: '静海'},
            {name: '南开'},
            {name: '宁河'},
            {name: '武清'},
            {name: '西青'},
        ],
    },
    {
        name: '西藏',
        items: [
            {name: '阿里'},
            {name: '昌都'},
            {name: '拉萨'},
            {name: '林芝'},
            {name: '那曲'},
            {name: '日喀则'},
            {name: '山南'},
        ],
    },
    {
        name: '新疆',
        items: [
            {name: '阿克苏'},
            {name: '阿拉尔'},
            {name: '阿勒泰'},
            {name: '巴音郭楞'},
            {name: '博尔塔拉'},
            {name: '昌吉'},
            {name: '哈密'},
            {name: '和田'},
            {name: '喀什'},
            {name: '克拉玛依'},
            {name: '克孜勒苏'},
            {name: '石河子'},
            {name: '塔城'},
            {name: '吐鲁番'},
            {name: '图木舒克'},
            {name: '五家渠'},
            {name: '乌鲁木齐'},
            {name: '伊犁'},
        ],
    },
    {
        name: '云南',
        items: [
            {name: '保山'},
            {name: '楚雄'},
            {name: '大理'},
            {name: '德宏'},
            {name: '迪庆'},
            {name: '红河'},
            {name: '昆明'},
            {name: '丽江'},
            {name: '临沧'},
            {name: '怒江'},
            {name: '普洱'},
            {name: '曲靖'},
            {name: '文山'},
            {name: '西双版纳'},
            {name: '玉溪'},
            {name: '昭通'},
        ],
    },
    {
        name: '浙江',
        items: [
            {name: '杭州'},
            {name: '湖州'},
            {name: '嘉兴'},
            {name: '金华'},
            {name: '丽水'},
            {name: '宁波'},
            {name: '衢州'},
            {name: '绍兴'},
            {name: '台州'},
            {name: '温州'},
            {name: '舟山'},
        ],
    },
    {
        name: '香港',
    },
    {
        name: '澳门',
    },
    {
        name: '台湾',
    },
]

export {
    residences,
    tailFormItemLayout,
    tailFormButtonLayout,
}